name: test
on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go:
          - '1.17.1'
          - '1.17.2'
    env:
      GOOS: js
      GOARCH: wasm
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: go run
        run: make run GO_VERSION=${{ matrix.go }}
